server:
  port: 8090
spring:
  application:
    name: loans
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/eazyms
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: "optional:configserver:http://localhost:8071/"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

  

