server:
  port: 8090
spring:
  application:
    name: loans
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/eazyms
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: "optional:configserver:http://localhost:8071/"


#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
        

endpoints:
  shutdown:
    enabled: true

 
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:  # under management
    env:
      enabled: true # this property will enable the below info.app.name etc in the eureka server dashboard
        
eureka:
  instance:
    preferIpAddress: true  # registers with eureka using IP address and not the dns /hostname.
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
      
      

info:
  app:
    name: "loans"
    description: "EazyBank loans Application"
    version: "1.0.0"